### ISSUE TITLE
Enable triggering build workflows on PRs, and specify order of workflows

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#149]
We need few improvements for the workflows:
- Trigger the build workflows for PRs on main. Also, enable manual triggers. For `build-test.yml`, it should be something as following
```
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'Specification/**'
      - 'Specification.EntityFrameworkCore/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Specification/**'
      - 'Specification.EntityFrameworkCore/**'
```
- Order of workflow execution. We need build tasks to happen before the publish tasks. If possible, if the build fails it shouldn't proceed with the publish tasks. I did a quick research and it seems [Repository Dispatch](https://github.com/marketplace/actions/repository-dispatch#example) is the only way? Any better idea?
